### ISSUE TITLE
Trouble starting up noderedrevpinodes-server due to unknown key names in systemd

### ISSUE THREAD

**Issue by gdfrancia** [erminas/noderedrevpinodes-server#16]
I keep on having this issue with systemd not being able to run due to it complaining about unknown keys in the service file for `noderedrevpinodes-server`. It doesn't start up at all because of this, and I was wondering what are the following keys supposed to be for?

```
MemoryAccounting=true
MemoryHigh=200M
MemoryMax=400M
```

Here's the output of `journalctl -xeu noderedrevpinodes-server.service` where it mentions the offending keys.

```
Sep 28 09:16:39 RevPiMainTitusNative systemd[1]: /lib/systemd/system/noderedrevpinodes-server.service:6: Unknown key name 'MemoryAccounting' in section 'Unit', ignoring.
Sep 28 09:16:39 RevPiMainTitusNative systemd[1]: /lib/systemd/system/noderedrevpinodes-server.service:7: Unknown key name 'MemoryHigh' in section 'Unit', ignoring.
Sep 28 09:16:39 RevPiMainTitusNative systemd[1]: /lib/systemd/system/noderedrevpinodes-server.service:8: Unknown key name 'MemoryMax' in section 'Unit', ignoring.
Sep 28 09:17:22 RevPiMainTitusNative systemd[1]: Started Revolution Pi NodeRed Service.
░░ Subject: A start job for unit noderedrevpinodes-server.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit noderedrevpinodes-server.service has finished successfully.
░░
░░ The job identifier is 52848.
Sep 28 09:17:22 RevPiMainTitusNative systemd[1]: noderedrevpinodes-server.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit noderedrevpinodes-server.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Sep 28 09:17:22 RevPiMainTitusNative systemd[1]: noderedrevpinodes-server.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit noderedrevpinodes-server.service has entered the 'failed' state with result 'exit-code'.

**Comment by hbunjes** [comment]
@gdfrancia 
I think the keys are not the reason for the service failure but just a warning/hint.

Is there a log file `/var/log/revpi-server.log` and if so, can you attach the content of the file?

Can you also give information about your system? 

- OS version: `lsb_release -a`
- Kernel version: `uname -a`
- SystemD version: `systemd --version`

Thank you,
Hilmar

**Comment by gdfrancia** [comment]
> @gdfrancia I think the keys are not the reason for the service failure but just a warning/hint.
> 
> Is there a log file `/var/log/revpi-server.log` and if so, can you attach the content of the file?
> 
> Can you also give information about your system?
> 
> * OS version: `lsb_release -a`
> * Kernel version: `uname -a`
> * SystemD version: `systemd --version`
> 
> Thank you, Hilmar


Here's the output of the following. I still don't understand what went wrong, as I don't really have that much familiarity with RevPi.

* `cat /var/log/revpi-server.log`:
```
2023-09-26 13:02:35,472 root        : WARNING  No configuration file was found. Default options applied.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1007, in get_jconfigrsc
    jdata = jload(fhconfigrsc)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 613, in <module>
    revPiServer = RevPiServer(port, block_external_connections)
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 154, in __init__
    self.initialize_revpimodio()
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 196, in initialize_revpimodio
    self.revpi = revpimodio2.RevPiModIO(autorefresh=True, shared_procimg=True)
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 166, in __init__
    self._configure(self.get_jconfigrsc())
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1009, in get_jconfigrsc
    raise RuntimeError(
RuntimeError: can not read piCtory configuration - check your hardware configuration http://revpi_ip/
2023-09-28 09:08:20,326 root        : WARNING  No configuration file was found. Default options applied.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1007, in get_jconfigrsc
    jdata = jload(fhconfigrsc)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 613, in <module>
    revPiServer = RevPiServer(port, block_external_connections)
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 154, in __init__
    self.initialize_revpimodio()
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 196, in initialize_revpimodio
    self.revpi = revpimodio2.RevPiModIO(autorefresh=True, shared_procimg=True)
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 166, in __init__
    self._configure(self.get_jconfigrsc())
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1009, in get_jconfigrsc
    raise RuntimeError(
RuntimeError: can not read piCtory configuration - check your hardware configuration http://revpi_ip/
2023-09-28 09:17:22,683 root        : WARNING  No configuration file was found. Default options applied.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1007, in get_jconfigrsc
    jdata = jload(fhconfigrsc)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 613, in <module>
    revPiServer = RevPiServer(port, block_external_connections)
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 154, in __init__
    self.initialize_revpimodio()
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 196, in initialize_revpimodio
    self.revpi = revpimodio2.RevPiModIO(autorefresh=True, shared_procimg=True)
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 166, in __init__
    self._configure(self.get_jconfigrsc())
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1009, in get_jconfigrsc
    raise RuntimeError(
RuntimeError: can not read piCtory configuration - check your hardware configuration http://revpi_ip/
2023-09-28 09:22:20,161 root        : WARNING  No configuration file was found. Default options applied.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1007, in get_jconfigrsc
    jdata = jload(fhconfigrsc)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 613, in <module>
    revPiServer = RevPiServer(port, block_external_connections)
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 154, in __init__
    self.initialize_revpimodio()
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 196, in initialize_revpimodio
    self.revpi = revpimodio2.RevPiModIO(autorefresh=True, shared_procimg=True)
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 166, in __init__
    self._configure(self.get_jconfigrsc())
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1009, in get_jconfigrsc
    raise RuntimeError(
RuntimeError: can not read piCtory configuration - check your hardware configuration http://revpi_ip/
2023-09-28 09:24:09,934 root        : WARNING  No configuration file was found. Default options applied.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1007, in get_jconfigrsc
    jdata = jload(fhconfigrsc)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 613, in <module>
    revPiServer = RevPiServer(port, block_external_connections)
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 154, in __init__
    self.initialize_revpimodio()
  File "/usr/share/noderedrevpinodes-server/revpi-server.py", line 196, in initialize_revpimodio
    self.revpi = revpimodio2.RevPiModIO(autorefresh=True, shared_procimg=True)
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 166, in __init__
    self._configure(self.get_jconfigrsc())
  File "/usr/lib/python3/dist-packages/revpimodio2/modio.py", line 1009, in get_jconfigrsc
    raise RuntimeError(
RuntimeError: can not read piCtory configuration - check your hardware configuration http://revpi_ip/
```

* `uname -a`
```
Linux RevPi 5.10.152-rt75-v8 #1 SMP PREEMPT_RT Tue, 12 Sep 2023 16:06:10 +0200 aarch64 GNU/Linux
```

* `systemd --version`
```
systemd 247 (247.3-7+deb11u4)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Comment by hbunjes** [comment]
As far as I see the initial setup step for the RevPi is missing: Creating the pictory configuration. This is the step where the modules of the RevPi are configured. This outputs a file that will be read by the RevPi Nodes server (it looks at: "/etc/revpi/config.rsc", "/opt/KUNBUS/config.rsc").

The tutorial on how to create the config is shown here: [Create Configuration File Pictory](https://revolutionpi.com/tutorials/what-is-pictory/create-configuration-file-pictory?noredirect=en-US) (You do not need an export of the configuration).

**Comment by gdfrancia** [comment]
> As far as I see the initial setup step for the RevPi is missing: Creating the pictory configuration. This is the step where the modules of the RevPi are configured. This outputs a file that will be read by the RevPi Nodes server (it looks at: "/etc/revpi/config.rsc", "/opt/KUNBUS/config.rsc").
> 
> The tutorial on how to create the config is shown here: [Create Configuration File Pictory](https://revolutionpi.com/tutorials/what-is-pictory/create-configuration-file-pictory?noredirect=en-US) (You do not need an export of the configuration).


ohh, that makes more sense. I guess I was too eager to setup RevPi that I didn't realise I have to setup Pictory. Thank you for the response. I'll close this for now, and I'll reopen if I still have an issue running `noderedrevpinodes-server`.
